### ISSUE TITLE
Location of NN network files?

### ISSUE THREAD

**Issue by kenpchess** [FireFather/fire#2]
Hello Norman. Fire-zero is coming along nicely! (I have always liked Fire!). 
I cannot seem to find the binary network files. Location please?

Thanks in advance - kenpchess

**Comment by FireFather** [comment]
Hi.  There's no need to load an external network, as the nnue is embedded (contained) in the engine binary.

**Comment by kenpchess** [comment]
Hello again. Well I am trying build this from source on a macintosh, and the make file cannot find the NN binay file to include. And I cannot find it either in your github source. Thanks in advance. - kenpchess

**Comment by FireFather** [comment]
[05152023-045758.zip](https://github.com/FireFather/fire-zero/files/11521141/05152023-045758.zip)

**Comment by kenpchess** [comment]
Thanks so much, Norman! It builds and runs fine now. FYI, on my mac-mini 2018 3.6 ghz quad-core i3 the standard perft 7 numbers are:

depth 7
nodes 3195901860
time 25.271 secs
nps 126465192

Thanks again!  - kenpchess
